### PR TITLE
Use elastic_beats_repo cookbook for managing repo

### PR DESCRIPTION
**Pull request by brianvans**
This makes the `elastic_beats_repo` cookbook responsible for managing the repo.  Also adds an attribute for users that wish to manage the repository themselves via a wrapper cookbook.

### CODE REVIEW

**Comment by vkhatri** [comment]
@brianvans 👍

**Comment by vkhatri** [comment]
@brianvans Could you please share your Chef Supermarket userId to add you as a Contributor?

**Comment by brianvans** [comment]
@vkhatri https://supermarket.chef.io/users/brianvans thanks!

**Comment by vkhatri** [comment]
Added to Supermarket too. Thanks!

**Pull request merged**
